export const TODO = 'TODO'
export const TODOS = 'TODOS'
export const TODOS_COUNT = 'TODOS_COUNT'
export const DONE_TODOS_COUNT = 'DONE_TODOS_COUNT'
export const FILTER = 'FILTER'
export const IS_COMPLETED = 'IS_COMPLETED'